### ISSUE TITLE
Help Wanted II

### ISSUE THREAD

**Issue by ctrl-alt-d** [ctrl-alt-d/Blagario#11]
Split https://github.com/ctrl-alt-d/Blagario/issues/1 into atomic issues linked to tasks and project milestones.

**Comment by EsteveAguilera** [comment]
On issue #1 you assigned a complexity level to each issue/task... Maybe it will be good to have a label for each complexity level?

**Comment by ctrl-alt-d** [comment]
Seems like a good idea.
